platform:
  - Win32
environment:
  PYTHON: "C:\\Python35"
build: off
install:
  - powershell -command "Start-FileDownload https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.bat -FileName %TEMP%/install-zpm.bat" && %TEMP%/install-zpm.bat 
  - "SET PATH=%PATH%;%USERPROFILE%/zpm/bin"
test_script:
  - cd test && zpm run test-definition cxxopts
