sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env: VERSION=6
  - os: linux
    dist: trusty
    env: VERSION=7
  - os: osx
    osx_image: xcode9.2
    language: generic
global:
  env:
  - PROJECT=cxxopts
  - PROJECT_TEMPLATE=default
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.sh)"
script:
- cd test && zpm run test-definition cxxopts
notifications:
  slack:
    secure: R5EUTR6JSDRXN2xLt3rNBJZUnN5nWMQH6ALj4okSaNRKy4OCZw52YI/wsh9o51lc5WcDBos/JR9Y8RbZ2CnT+zhG947kUFjtpr45scotBE3ZpsOmVqTkdjp6IJtQK0bVq8bVIkYseoTsTM2tJNdvpTH9KrOWSdiUswH/eezGChX9wze3YFKQbvg5zKZmYb9CpDD8Ek9onVRqVBpEEo/Wm3x/xojOsfwYG6/qlWWpSdn3cr+/6CSNZ917aY1ihDRN+ooh6Ak7UQ2r8lK+fxRJ14yNsYXNhPrvGA9oi0h43t4wRc4sTBV0OZK+ei/5L6Pi3QbPdHF/0MYmuEc9g8mayxpbo3Wfz4c3pItgWra0bJXQPGd+FHWoi7Fam7BqC2or1aTJWmUvnDPbPUPaL7enr6UP2+8nsH0eQG7LQcNJUYg4BjvpacfNvH41VrtTFqU2Mvfv7MsRtQp/c0kLRamAZ205F5PWfKOKxm2FcNVVATtF0U3mgljMCp4jn/6Oz4K/l1h3KTI7qwyeKd/v8XWYgldbSxnAUKRgrTs9EbBWBw4YPP1N/wavPa+vwDnK7nNgpJADq5q3mtAv8ow8xFSXQ+bwojzYMXxzEDREQ5PGqvJg1JzRm0ISrhwSFL9trXAFH9Ee15bJW1fPdGaSwEI+EeQ95FASDVG2AgZFe/ZF2Jg=
